//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_LU_SCM_REPORT_ACCESS_REMOVED
    {
        public string REPORT_NAME_IN_TOOLBOX { get; set; }
        public string USER_GID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_SOM_ORG_CODE { get; set; }
        public string USER_DEPT { get; set; }
        public string USER_PMP_MANAGER { get; set; }
        public string REMOVE_MONTH { get; set; }
        public string REPORT_LINK { get; set; }
        public string RECORD_STATUS { get; set; }
        public string APPIDS { get; set; }
    }
}
