//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Access
    {
        public int a_ID { get; set; }
        public string a_Name { get; set; }
        public Nullable<int> a_Type_R { get; set; }
        public Nullable<int> a_Type_C { get; set; }
        public Nullable<int> a_Type_U { get; set; }
        public Nullable<int> a_Type_D { get; set; }
        public Nullable<int> a_Sort { get; set; }
    }
}
