//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Customization
    {
        public int c_ID { get; set; }
        public string c_GUID { get; set; }
        public Nullable<int> c_m_DeptID { get; set; }
        public string c_Name { get; set; }
        public string c_Category { get; set; }
        public string c_Description { get; set; }
        public string c_PicPath { get; set; }
        public string c_Linkage { get; set; }
        public Nullable<int> c_Sort { get; set; }
        public string c_Owner { get; set; }
    }
}
