//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Entry
    {
        public int e_ID { get; set; }
        public Nullable<int> e_Dept_ID { get; set; }
        public string e_Dept_FullName { get; set; }
        public string e_Dept_AbbreviatedName { get; set; }
        public string e_ControllerName { get; set; }
        public Nullable<bool> e_Enabled { get; set; }
        public Nullable<int> e_AccessLevel { get; set; }
    }
}
