//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_LanguageProfile
    {
        public int lp_ID { get; set; }
        public string lp_u_GID { get; set; }
        public Nullable<int> lp_LanguageType { get; set; }
    }
}
