//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Menu
    {
        public int m_ID { get; set; }
        public int m_ParentID { get; set; }
        public Nullable<int> m_e_ID { get; set; }
        public int m_DeptID { get; set; }
        public string m_MenuName { get; set; }
        public string m_ActionName { get; set; }
        public Nullable<int> m_AccessLevel { get; set; }
        public Nullable<bool> m_IsGeneral { get; set; }
        public Nullable<int> m_Sort { get; set; }
    }
}
