//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ProcessNode
    {
        public int pn_ID { get; set; }
        public Nullable<int> pn_m_DeptID { get; set; }
        public Nullable<int> pn_m_ID { get; set; }
        public string pn_NodeName { get; set; }
        public string pn_Owner { get; set; }
        public Nullable<int> pn_Position_X { get; set; }
        public Nullable<int> pn_Position_Y { get; set; }
    }
}
