//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ProcessLinkage
    {
        public int pl_ID { get; set; }
        public Nullable<int> pl_pn_ID { get; set; }
        public Nullable<int> pl_Type { get; set; }
        public string pl_Name { get; set; }
        public string pl_Linkage { get; set; }
        public Nullable<int> pl_Sort { get; set; }
    }
}
