//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ProcessConnection
    {
        public int pc_ID { get; set; }
        public Nullable<int> pc_m_DeptID { get; set; }
        public Nullable<int> pc_m_ID { get; set; }
        public Nullable<int> pc_Node_ID { get; set; }
        public Nullable<int> pc_NextNode_ID { get; set; }
        public Nullable<int> pc_ConnectionType { get; set; }
        public string pc_ConnectionLabel { get; set; }
    }
}
