//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_QuickLink
    {
        public int ql_ID { get; set; }
        public string ql_GUID { get; set; }
        public Nullable<int> ql_m_DeptID { get; set; }
        public Nullable<int> ql_m_ID { get; set; }
        public string ql_Name { get; set; }
        public string ql_Description { get; set; }
        public string ql_PicPath { get; set; }
        public string ql_Linkage { get; set; }
        public Nullable<int> ql_Status { get; set; }
        public Nullable<int> ql_AccessLevel { get; set; }
        public Nullable<int> ql_Sort { get; set; }
    }
}
