//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ReportIssue
    {
        public int id { get; set; }
        public int r_Id { get; set; }
        public string Issues { get; set; }
        public string Issusue_title { get; set; }
        public string Issue_image { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime Createtime { get; set; }
        public string ReportTitle { get; set; }
        public string AdminOwner { get; set; }
        public string AdminOwnerName { get; set; }
        public string AnswerReason { get; set; }
        public string AnswerDetail { get; set; }
        public string HandleUser { get; set; }
        public string HandleUserName { get; set; }
        public Nullable<System.DateTime> HandleTime { get; set; }
        public string CreateUserName { get; set; }
        public short State { get; set; }
        public short Groups { get; set; }
    }
}
