//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Report_ClickStatistics
    {
        public int r_cs_ID { get; set; }
        public int r_cs_r_ID { get; set; }
        public int r_cs_ClickTimes { get; set; }
        public int r_cs_ForYear { get; set; }
        public int r_cs_ForMonth { get; set; }
        public Nullable<int> r_cs_ForDay { get; set; }
        public string r_cs_User_GID { get; set; }
        public System.DateTime r_cs_LastUpdateDate { get; set; }
    }
}
