//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Report
    {
        public int r_ID { get; set; }
        public string r_GUID { get; set; }
        public Nullable<int> r_m_DeptID { get; set; }
        public Nullable<int> r_m_ID_Category { get; set; }
        public Nullable<int> r_m_ID_Frequency { get; set; }
        public string r_Name { get; set; }
        public string r_Description { get; set; }
        public string r_Owner { get; set; }
        public string r_AccessOwner { get; set; }
        public string r_PicPath { get; set; }
        public string r_Linkage { get; set; }
        public Nullable<int> r_Status { get; set; }
        public Nullable<int> r_AccessLevel { get; set; }
        public Nullable<int> r_Sort { get; set; }
        public string r_Admin { get; set; }
        public Nullable<int> r_m_ID_SubCategory { get; set; }
        public string r_CROwner { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string r_APPIDS { get; set; }
    }
}
