//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sys_TypeDescription
    {
        public int td_ID { get; set; }
        public string td_TableName { get; set; }
        public string td_ColumnName { get; set; }
        public Nullable<int> td_TypeID { get; set; }
        public string td_TypeDescription { get; set; }
    }
}
