//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_MenuList
    {
        public long ml_RowNum { get; set; }
        public int ml_Main_ID { get; set; }
        public Nullable<int> ml_Main_e_ID { get; set; }
        public int ml_Main_DeptID { get; set; }
        public string ml_e_ControllerName { get; set; }
        public string ml_Main_MenuName { get; set; }
        public string ml_Main_ActionName { get; set; }
        public Nullable<int> ml_Main_AccessLevel { get; set; }
        public Nullable<bool> ml_Main_IsGeneral { get; set; }
        public Nullable<int> ml_Sub_ID { get; set; }
        public string ml_Sub_MenuName { get; set; }
        public string ml_Sub_ActionName { get; set; }
        public int ml_Sub_AccessLevel { get; set; }
        public bool ml_Sub_IsGeneral { get; set; }
        public Nullable<int> ml_Third_ID { get; set; }
        public string ml_Third_MenuName { get; set; }
        public string ml_Third_ActionName { get; set; }
        public int ml_Third_AccessLevel { get; set; }
        public bool ml_Third_IsGeneral { get; set; }
        public Nullable<int> ml_Fourth_ID { get; set; }
        public string ml_Fourth_MenuName { get; set; }
        public string ml_Fourth_ActionName { get; set; }
        public int ml_Fourth_AccessLevel { get; set; }
        public bool ml_Fourth_IsGeneral { get; set; }
    }
}
