//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Report_ClickStatistics
    {
        public string ReportName { get; set; }
        public int ReportId { get; set; }
        public Nullable<int> ClickTimes { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string YearMonth { get; set; }
        public Nullable<int> frequencyId { get; set; }
        public string Frequency { get; set; }
    }
}
