//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.DAL.EFs
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_User
    {
        public int User_ID { get; set; }
        public string User_GID { get; set; }
        public string User_DisplayText { get; set; }
        public string User_Name_EN { get; set; }
        public string User_Name_CH { get; set; }
        public string User_EmployeeNumber { get; set; }
        public string User_Email { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public string Job_Function { get; set; }
        public string Job_IsManager { get; set; }
        public Nullable<int> LineManager_ID { get; set; }
        public string LineManager_Name_EN { get; set; }
        public string LineManager_Name_CH { get; set; }
        public string LineManager_GID { get; set; }
        public string LineManager_DisplayText { get; set; }
        public string LineManager_EMAIL { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<int> Dept_ParentID { get; set; }
        public string Dept_IsPrimary { get; set; }
        public string Dept_FullName { get; set; }
        public string Dept_AbbreviatedName { get; set; }
    }
}
