//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEWC_ToolBox.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SSOServiceSoap")]
    public interface SSOServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserToken", ReplyAction="*")]
        SEWC_ToolBox.ServiceReference1.GetUserTokenResponse GetUserToken(SEWC_ToolBox.ServiceReference1.GetUserTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserToken", ReplyAction="*")]
        System.Threading.Tasks.Task<SEWC_ToolBox.ServiceReference1.GetUserTokenResponse> GetUserTokenAsync(SEWC_ToolBox.ServiceReference1.GetUserTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserToken", Namespace="http://tempuri.org/", Order=0)]
        public SEWC_ToolBox.ServiceReference1.GetUserTokenRequestBody Body;
        
        public GetUserTokenRequest() {
        }
        
        public GetUserTokenRequest(SEWC_ToolBox.ServiceReference1.GetUserTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public GetUserTokenRequestBody() {
        }
        
        public GetUserTokenRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public SEWC_ToolBox.ServiceReference1.GetUserTokenResponseBody Body;
        
        public GetUserTokenResponse() {
        }
        
        public GetUserTokenResponse(SEWC_ToolBox.ServiceReference1.GetUserTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserTokenResult;
        
        public GetUserTokenResponseBody() {
        }
        
        public GetUserTokenResponseBody(string GetUserTokenResult) {
            this.GetUserTokenResult = GetUserTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SSOServiceSoapChannel : SEWC_ToolBox.ServiceReference1.SSOServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSOServiceSoapClient : System.ServiceModel.ClientBase<SEWC_ToolBox.ServiceReference1.SSOServiceSoap>, SEWC_ToolBox.ServiceReference1.SSOServiceSoap {
        
        public SSOServiceSoapClient() {
        }
        
        public SSOServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSOServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSOServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSOServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SEWC_ToolBox.ServiceReference1.GetUserTokenResponse SEWC_ToolBox.ServiceReference1.SSOServiceSoap.GetUserToken(SEWC_ToolBox.ServiceReference1.GetUserTokenRequest request) {
            return base.Channel.GetUserToken(request);
        }
        
        public string GetUserToken(string userId) {
            SEWC_ToolBox.ServiceReference1.GetUserTokenRequest inValue = new SEWC_ToolBox.ServiceReference1.GetUserTokenRequest();
            inValue.Body = new SEWC_ToolBox.ServiceReference1.GetUserTokenRequestBody();
            inValue.Body.userId = userId;
            SEWC_ToolBox.ServiceReference1.GetUserTokenResponse retVal = ((SEWC_ToolBox.ServiceReference1.SSOServiceSoap)(this)).GetUserToken(inValue);
            return retVal.Body.GetUserTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SEWC_ToolBox.ServiceReference1.GetUserTokenResponse> SEWC_ToolBox.ServiceReference1.SSOServiceSoap.GetUserTokenAsync(SEWC_ToolBox.ServiceReference1.GetUserTokenRequest request) {
            return base.Channel.GetUserTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SEWC_ToolBox.ServiceReference1.GetUserTokenResponse> GetUserTokenAsync(string userId) {
            SEWC_ToolBox.ServiceReference1.GetUserTokenRequest inValue = new SEWC_ToolBox.ServiceReference1.GetUserTokenRequest();
            inValue.Body = new SEWC_ToolBox.ServiceReference1.GetUserTokenRequestBody();
            inValue.Body.userId = userId;
            return ((SEWC_ToolBox.ServiceReference1.SSOServiceSoap)(this)).GetUserTokenAsync(inValue);
        }
    }
}
